"""initial connect

Revision ID: 6438d8a0a58d
Revises: 
Create Date: 2024-08-06 12:52:22.852669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6438d8a0a58d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_symbol', sa.Integer(), nullable=True),
    sa.Column('ask', sa.Text(), nullable=True),
    sa.Column('bid', sa.Text(), nullable=True),
    sa.Column('time_open', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('time_update', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_symbol'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_book_id_symbol'), 'order_book', ['id_symbol'], unique=False)
    op.create_index(op.f('ix_order_book_time_open'), 'order_book', ['time_open'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_book_time_open'), table_name='order_book')
    op.drop_index(op.f('ix_order_book_id_symbol'), table_name='order_book')
    op.drop_table('order_book')
    # ### end Alembic commands ###
